### ISSUE TITLE
K8S Helm Chart 部署后 503 

### ISSUE THREAD

**Issue by linonetwo** [nacos-group/r-nacos#111]
访问 `https://config.xxx.site/rnacos/`

修改后的 values 为

```yaml
# Default values for rnacos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: core.image-registry.xxx.site/mirror-manual/qingpan/rnacos
  pullPolicy: Always # IfNotPresent #
  # Overrides the image tag whose default is the chart appVersion.
  tag: v0.5.13

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rancosConfig:
  rustLog: info
  httpWorkers: 8
  consoleLoginOneHourLimit: 5

persistence:
  size: 20Gi
  storageClass: default
  accessModes: ["ReadWriteOnce"]
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 10848

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: config.xxx.site
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-secret
      hosts:
        - config.xxx.site

resources:
  limits:
    cpu: 2000m
    memory: 1280Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

```

部署时有警告

```
helm upgrade --install r-nacos ./r-nacos --namespace configuration-center
Release "r-nacos" does not exist. Installing it now.
W0628 00:22:13.944299 2203128 warnings.go:70] unknown field "spec.template.spec.containers[0].livenessProbe.tcpSocket.service"
W0628 00:22:13.944326 2203128 warnings.go:70] unknown field "spec.template.spec.containers[0].readinessProbe.tcpSocket.service"
NAME: r-nacos
LAST DEPLOYED: Fri Jun 28 00:22:13 2024
NAMESPACE: configuration-center
STATUS: deployed
REVISION: 1
```
