### ISSUE TITLE
添加一下 docker compsoe 方便部署

### ISSUE THREAD

**Issue by zoujiaqing** [nacos-group/r-nacos#120]
现在已经传到 docker hub 了，因为大家对 r-nacos 的配置和设置不太熟悉，可以增加一个 `docker-compose.yml` 类似如下格式：

```yml
version: '3.9'

services:
  rnacos:
    image: qingpan/rnacos:stable
    ports:
      - 8848:8848
      - 9848:9848
    volumes:
      - ./data:/var/lib/rnacos/data
    environment:
      - RNACOS_INIT_ADMIN_USERNAME=admin
      - RNACOS_INIT_ADMIN_PASSWORD=123456
      - RNACOS_HTTP_PORT=8848
      - RNACOS_GRPC_PORT=9848
      - RNACOS_RAFT_NODE_ID=1
```
