### ISSUE TITLE
Docker 部署 不能访问  外网 ip:10848/rancos

### ISSUE THREAD

**Issue by Avey777** [nacos-group/r-nacos#158]
```
# 集群部署样例,数据目录: ./data
version: '3.8'

services:
  nacos:
    image: qingpan/rnacos:stable
    container_name: rnacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "10848:10848"
    volumes:
      - ./data:/io:rw
    environment:
      - RNACOS_INIT_ADMIN_USERNAME=admin
      - RNACOS_INIT_ADMIN_PASSWORD=admin
      - RNACOS_HTTP_PORT=8848
      - RNACOS_RAFT_AUTO_INIT=true
      - RNACOS_HTTP_CONSOLE_PORT=10848
      - RNACOS_ENABLE_NO_AUTH_CONSOLE=false
    restart: always

```

http://192.210.197.70:10848/rnacos

![image](https://github.com/user-attachments/assets/e98d1b59-57d6-4cc0-b148-6fe62dd1670a)
