### ISSUE TITLE
服务注册 只能注册到public命名空间下面 这个和nacos 不一样

### ISSUE THREAD

**Issue by fmkj-hhh** [nacos-group/r-nacos#197]

**Comment by heqingpan** [comment]
这个是基本功能，肯定是支持的。

你是使用什么方式调用，是否有明确指定其它命名空间？
可以把你使用的配置方式提供一下，一起看看。

**Comment by fmkj-hhh** [comment]
> 这个是基本功能，肯定是支持的。
> 
> 你是使用什么方式调用，是否有明确指定其它命名空间？ 可以把你使用的配置方式提供一下，一起看看。

使用的是java 的sdk，用的是springcloud alibaba 里面的配置中心 和 注册中心
注册中心 设置了命名空间 prod 但是却注册到了 public命名空间

**Comment by heqingpan** [comment]
服务端、客户端都是支持多命名空间运行的。

每个sdk都有设置命名空间的入口，如果你找不到，可以把你的sdk client配置代码发出来，我再帮你看看。

**Comment by heqingpan** [comment]
给个spring-cloud包含指定命名空间的配置给你参考：

```yaml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848} # Nacos 服务器地址
        namespace: ${NACOS_NAMESPACE:your-namespace-id}  # 指定命名空间 ID
        username: ${NACOS_USERNAME:your-username}        # Nacos 用户名
        password: ${NACOS_PASSWORD:your-password}        # Nacos 密码
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848} # Nacos 服务器地址
        namespace: ${NACOS_NAMESPACE:your-namespace-id}  # 指定命名空间 ID
        username: ${NACOS_USERNAME:your-username}        # Nacos 用户名
        password: ${NACOS_PASSWORD:your-password}        # Nacos 密码
        file-extension: yaml                              # 配置文件格式（如 yaml 或 properties）
```
